name: Deploy Firebase Studio to GitHub Pages

on:
  push:
    branches: [ main, master ]
    paths:
      - 'firebase-studio-frontend/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'firebase-studio-frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: firebase-studio-frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd firebase-studio-frontend
        npm ci
        
    - name: Build
      run: |
        cd firebase-studio-frontend
        npm run build
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./firebase-studio-frontend/dist
        cname: # Optional: add your custom domain here
        
    - name: Comment PR with preview link
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && comment.body.includes('Preview deployment')
          );
          
          const previewUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/firebase-studio-frontend/`;
          
          const body = `🚀 **Preview Deployment Ready!**
          
          Your Firebase Studio changes are ready for preview:
          
          🔗 **Preview URL**: ${previewUrl}
          
          📱 **PWA Features**: 
          - Installable on mobile and desktop
          - Offline functionality
          - Smooth animations and transitions
          - Responsive design
          
          ⚡ **Performance**: 
          - Optimized bundle with code splitting
          - Service worker caching
          - Modern UI with Revolut-inspired design
          
          ---
          *This preview will be updated automatically when you push new changes.*`;
          
          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
          }
