name: Hologram SDK Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
    
    - name: Run tests
      run: |
        cd tests
        chmod +x run_all.sh
        ./run_all.sh
    
    - name: Upload daemon logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: hologramd-logs
        path: /tmp/hologram-artifacts/
        retention-days: 7
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          tests/go/golden/
          /tmp/hologram-artifacts/test-summary.json
        retention-days: 7
    
    - name: Comment PR with results
      if: always() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = '/tmp/hologram-artifacts/test-summary.json';
          
          if (fs.existsSync(path)) {
            const summary = JSON.parse(fs.readFileSync(path, 'utf8'));
            
            let comment = '## 🧪 Hologram SDK Test Results\n\n';
            
            if (summary.status === 'success') {
              comment += '✅ **All tests passed!**\n\n';
              comment += '| Mode | Status |\n';
              comment += '|------|--------|\n';
              comment += '| Compat | ✅ Passed |\n';
              comment += '| Verbose | ✅ Passed |\n';
              comment += '| Enforce | ✅ Passed |\n';
            } else {
              comment += '❌ **Some tests failed**\n\n';
              comment += 'Failed modes: ' + summary.failed_modes.join(', ') + '\n\n';
              comment += 'Check the artifacts for detailed logs.\n';
            }
            
            comment += '\n---\n';
            comment += '*Generated by Hologram SDK CI*';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          }
