name: perf
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npm run bench:ci
      - run: npm run bench:verify -- --min-ops-per-sec=10000
      - name: Upload perf attestation
        uses: actions/upload-artifact@v4
        with:
          name: perf-attestation
          path: artifacts/perf/attestation.json
