name: sdk-smoke
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        lang: [node, python, go, rust, c]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Toolchains per language (node always available)
      - name: Setup Python
        if: matrix.lang == 'python'
        uses: actions/setup-python@v5
        with: 
          python-version: '3.11'
          cache: 'pip'

      - name: Setup Go
        if: matrix.lang == 'go'
        uses: actions/setup-go@v5
        with: 
          go-version: '1.22'
          cache: true

      - name: Setup Rust
        if: matrix.lang == 'rust'
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        if: matrix.lang == 'rust'
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Run the smoke command with performance monitoring
      - name: Run smoke test
        env:
          HOLOGRAM_SDK_REF: npx ts-node --transpile-only sdk/ref/cli.ts
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          echo "🚀 Testing ${{ matrix.lang }} SDK..."
          time npm run sdk:smoke:${{ matrix.lang }}
          echo "✅ ${{ matrix.lang }} SDK smoke test completed successfully"

      # Enhanced output with performance metrics
      - name: Show results
        if: always()
        run: |
          echo "📊 SDK Smoke Test Results for ${{ matrix.lang }}:"
          echo "  - Status: ${{ job.status }}"
          echo "  - Output above shows JSON response from version call"
